#!/usr/bin/env bash

RRD_FILE_NAME='/var/muzaiko/auxskultantoj.rrd'
RRDTOOL='/opt/rrdtool-1.4.5/bin/rrdtool'
CURRENT_TIMESTAMP=$(date '+%s')

if [ ! -f ${RRD_FILE_NAME} ]
then
	STEP=60
	DATA_SOURCE_TYPE='GAUGE'
	HEARTBEAT=$((STEP * 2))
	MIN_VALUE=0
	MAX_VALUE=U
	XFF=0.5

	VARIABLE_NAME='auxskultantoj'

	AVERAGE_AUXSKULTANTOJ_CF='AVERAGE'
	MINIMUM_AUXSKULTANTOJ_CF='MIN'
	MAXIMUM_AUXSKULTANTOJ_CF='MAX'

	MINUTE_STEP=1
	MINUTE_ROWS=1440 # high resolution day

	FIVE_MINUTES_STEP=5
	FIVE_MINUTES_ROWS=2016 # high resolution week

	FIFTEEN_MINUTES_STEP=15
	FIFTEEN_MINUTES_ROWS=3976 # high resolution month

	HOUR_STEP=60
	HOUR_ROWS=8784 # high resolution year

	DAY_STEP=1440
	DAY_ROWS=3660 # high resolution decade

	${RRDTOOL} create "${RRD_FILE_NAME}" \
		--start 1322882810 \
		--step "${STEP}" \
		"DS:${VARIABLE_NAME}:${DATA_SOURCE_TYPE}:${HEARTBEAT}:${MIN_VALUE}:${MAX_VALUE}" \
		"RRA:${AVERAGE_AUXSKULTANTOJ_CF}:${XFF}:${MINUTE_STEP}:${MINUTE_ROWS}" \
		"RRA:${MINIMUM_AUXSKULTANTOJ_CF}:${XFF}:${MINUTE_STEP}:${MINUTE_ROWS}" \
		"RRA:${MAXIMUM_AUXSKULTANTOJ_CF}:${XFF}:${MINUTE_STEP}:${MINUTE_ROWS}" \
		"RRA:${AVERAGE_AUXSKULTANTOJ_CF}:${XFF}:${FIVE_MINUTES_STEP}:${FIVE_MINUTES_ROWS}" \
		"RRA:${MINIMUM_AUXSKULTANTOJ_CF}:${XFF}:${FIVE_MINUTES_STEP}:${FIVE_MINUTES_ROWS}" \
		"RRA:${MAXIMUM_AUXSKULTANTOJ_CF}:${XFF}:${FIVE_MINUTES_STEP}:${FIVE_MINUTES_ROWS}" \
		"RRA:${AVERAGE_AUXSKULTANTOJ_CF}:${XFF}:${FIFTEEN_MINUTES_STEP}:${FIFTEEN_MINUTES_ROWS}" \
		"RRA:${MINIMUM_AUXSKULTANTOJ_CF}:${XFF}:${FIFTEEN_MINUTES_STEP}:${FIFTEEN_MINUTES_ROWS}" \
		"RRA:${MAXIMUM_AUXSKULTANTOJ_CF}:${XFF}:${FIFTEEN_MINUTES_STEP}:${FIFTEEN_MINUTES_ROWS}" \
		"RRA:${AVERAGE_AUXSKULTANTOJ_CF}:${XFF}:${HOUR_STEP}:${HOUR_ROWS}" \
		"RRA:${MINIMUM_AUXSKULTANTOJ_CF}:${XFF}:${HOUR_STEP}:${HOUR_ROWS}" \
		"RRA:${MAXIMUM_AUXSKULTANTOJ_CF}:${XFF}:${HOUR_STEP}:${HOUR_ROWS}" \
		"RRA:${AVERAGE_AUXSKULTANTOJ_CF}:${XFF}:${DAY_STEP}:${DAY_ROWS}" \
		"RRA:${MINIMUM_AUXSKULTANTOJ_CF}:${XFF}:${DAY_STEP}:${DAY_ROWS}" \
		"RRA:${MAXIMUM_AUXSKULTANTOJ_CF}:${XFF}:${DAY_STEP}:${DAY_ROWS}"
fi

[ -w "${RRD_FILE_NAME}" ] || exit 1

CURL='curl'

URL="http://api.radionomy.com/currentaudience.cfm?radiouid=14694a7d-9023-4db1-86b4-d85d96cba181"

AUXSKULTANTOJ=$(${CURL} --silent "${URL}")

#${RRDTOOL} update "${RRD_FILE_NAME}" ${CURRENT_TIMESTAMP}:${AUXSKULTANTOJ}

